### ISSUE TITLE
Problem to jump back from C source

### ISSUE THREAD

**Issue by yangchenyun** [purcell/elisp-slime-nav#14]
Once a native C function source code buffer is loaded, the binding M-, become ineffective and could not jump back to previous positions. 

Is it possible to enable elisp-slime-nav-mode for the new buffer where it founds the source code?

**Comment by purcell** [comment]
> Is it possible to enable elisp-slime-nav-mode for the new buffer where it founds the source code?

The solution is for you to bind `M-,` to `pop-tag-mark` in `c-mode`. I'll note this in the documentation somewhere.

**Comment by purcell** [comment]
In fact, I see that I've already noted in the documentation that `M-*` will do what you want in the C code, and also in `elisp-slime-nav-mode`.

**Comment by yangchenyun** [comment]
Thanks, see note in the source code. 
M-, is bound to another func in etags.el which I am using, but M-* is pretty neat!

**Comment by purcell** [comment]
If you prefer, you can just use M-* everywhere: M-, is bound to exactly the same function in elisp-slime-nav.
