### ISSUE TITLE
Jump to a ielm buffer on `C-c C-z`

### ISSUE THREAD

**Issue by bbatsov** [purcell/elisp-slime-nav#18]
That's another nice touch that'd be appreciated by Slime/Cider users. I've got something similar in Prelude, but I think it really belongs to a package like `elisp-slime-nav` (see https://github.com/bbatsov/prelude/blob/master/modules/prelude-emacs-lisp.el#L51).

**Comment by purcell** [comment]
Thanks. I have [an implementation of this in my config](https://github.com/purcell/emacs.d/blob/master/lisp/init-lisp.el#L52-L76) too, which is already quite different to yours.

My main reservation re. this issue (and similarly with #17) is that currently `elisp-slime-nav` doesn't need to know anything about the major mode in which it is enabled, so it works exactly the same in `ielm-mode` and `emacs-lisp-mode`.

Both this suggested change and #17 would require `elisp-slime-nav` to behave differently in those modes, and I'd probably rather avoid adding any fiddly functionality like that - I kinda like that the package in its current form does a couple of simple things well, and not much can go wrong.

**Comment by purcell** [comment]
P.S. Have you tried the `repl-toggle` package? That seems like it aims to be the general solution to making `C-c C-z` work everywhere, though I haven't really used it myself.

**Comment by purcell** [comment]
Circling back round to this, I'm going to pass due to reasoning above. Thanks though.
