### ISSUE TITLE
Can you configure this package for use within org-mode code blocks?

### ISSUE THREAD

**Issue by atanasj** [purcell/elisp-slime-nav#19]
Hi, 

Just wondering, can you use this package within `org-mode` code blocks?

Cheers,
Atanas.

**Comment by purcell** [comment]
I don't use org-mode code blocks really, so I'm not sure how you would do that. But the functions in this package should work, so I think the answer is "almost certainly yes".

**Comment by atanasj** [comment]
Awesome, got it working. For posterity, this is what I entered:

```emacs-lisp
(use-package elisp-slime-nav
    :config
    (dolist (hook '(emacs-lisp-mode-hook ielm-mode-hook))
      (add-hook hook 'turn-on-elisp-slime-nav-mode))
    :hook
    (org-mode . elisp-slime-nav-mode)
    )
```

May be a better way to do this, but this seems to work. 

Thanks again.

**Comment by purcell** [comment]
Looks good to me! Glad you got it working. BTW, I just marked `turn-on-elisp-slime-nav-mode` as obsolete: you should just use `elisp-slime-nav-mode` instead there.
