### ISSUE TITLE
Bind `elisp-slime-nav-describe-elisp-thing-at-point` to `C-c C-d`.

### ISSUE THREAD

**Issue by isolet** [purcell/elisp-slime-nav#21]
Hi, I am wondering how to bind `elisp-slime-nav-describe-elisp-thing-at-point` to `C-c C-d`. I try try unbind `C-c C-d d` and `C-c C-d C-d` using `(unbind-key "C-c C-d d" elisp-slime-nav-mode-map)` but I get error like `Debugger entered--Lisp error: (error "Key sequence C-c C-d d starts with non-prefix key ...")`. Without unbinding those, it seems that I cant get it bound to `C-c C-d`. Thanks!

**Comment by purcell** [comment]
Sorry, I'm not familiar with the `bind-key` package, and I think this question is really about that package: there's nothing unusual that `elisp-slime-nav` is doing here.

**Comment by isolet** [comment]
Hi, thanks for the reply. The same error comes when I try to use `define-key`
```
  (define-key elisp-slime-nav-mode-map (kbd "C-c C-d d") nil)
  (define-key elisp-slime-nav-mode-map (kbd "C-c C-d C-d") nil)
```

But something like 

```
(define-key vc-prefix-map "g" nil)
```

just works.

I know the issue it's not pretty much about `elisp-slime-nav`. But since the package use prefix keys, I would expect it should work like explicit prefix maps like `vc-prefix-map`. I now find `(define-key elisp-slime-nav-mode-map "d" nil)` works instead of `(define-key elisp-slime-nav-mode-map "C-d C-d d" nil)`.

**Comment by purcell** [comment]
Yeah, I might switch to a prefix map at some point, but it's not automatically better to do that: I don't necessarily want to "claim" the entire `C-c C-d` prefix, for example. The method I've used here lets other modes define `C-c C-d` bindings.
